//
//  GameWordBank.swift
//  HangInThere
//
//  Created by Codex on 12/03/26.
//

import Foundation

enum GameWordBank {
    static let wordsByCategoryAndLevel: [HangmanCategory: [GameLevel: [HangmanWord]]] = [
        .animals: leveledWords(from: animals),
        .geography: leveledWords(from: geography),
        .foods: leveledWords(from: foods),
        .objects: leveledWords(from: objects)
    ]

    private static let animals: [HangmanWord] = [
        word("Axolotl", "Salamander known for keeping its external gills", 3),
        word("Barracuda", "Predatory fish with a long, narrow body", 2),
        word("Caracal", "Wild cat with distinctive black ear tufts", 3),
        word("Cassowary", "Large flightless bird with a casque", 3),
        word("Cuttlefish", "Cephalopod with excellent camouflage", 3),
        word("Dromedary", "Single-humped camel adapted to deserts", 2),
        word("Echidna", "Egg-laying mammal covered in spines", 3),
        word("Frigatebird", "Seabird famous for its inflated red throat pouch", 3),
        word("Gharial", "Fish-eating crocodilian with a narrow snout", 3),
        word("Ibex", "Wild mountain goat with curved horns", 2),
        word("Jackrabbit", "Long-eared hare built for speed", 2),
        word("Kakapo", "Large flightless parrot from New Zealand", 3),
        word("Lamprey", "Jawless fish that attaches with a suction mouth", 3),
        word("Manatee", "Slow-moving marine mammal called a sea cow", 2),
        word("Narwhal", "Arctic whale with a long spiral tusk", 2),
        word("Ocelot", "Spotted wild cat from the Americas", 2),
        word("Pangolin", "Scale-covered mammal that feeds on ants", 3),
        word("Quoll", "Small carnivorous marsupial from Australia", 3),
        word("Raccoon Dog", "Canid native to East Asia with a masked face", 3),
        word("Secretary Bird", "Tall African bird that hunts snakes on foot", 3),
        word("Tarsier", "Tiny primate with enormous eyes", 3),
        word("Uakari", "Amazonian monkey known for its bright red face", 3),
        word("Vaquita", "Critically endangered porpoise from the Gulf of California", 3),
        word("Wallaroo", "Marsupial between a kangaroo and a wallaby", 3),
        word("Xantus Hummingbird", "Hummingbird native to Baja California", 3),
        word("Yellowhammer", "Songbird with bright yellow plumage", 3),
        word("Zorilla", "Striped African mammal also called a polecat", 3),
        word("Aye Aye", "Lemur that taps wood to find insects", 3),
        word("Binturong", "Tree-dwelling mammal sometimes called a bearcat", 3),
        word("Coelacanth", "Ancient lobe-finned fish once thought extinct", 3),
        word("Dugong", "Marine herbivore related to the manatee", 3),
        word("Eland", "Large antelope native to Africa", 2),
        word("Fossa", "Madagascar predator related to mongooses", 3),
        word("Galago", "Nocturnal primate also called a bush baby", 3),
        word("Hoatzin", "Leaf-eating bird with a distinctive crest", 3),
        word("Indri", "Large lemur known for its loud calls", 3),
        word("Jerboa", "Desert rodent with long hopping legs", 3),
        word("Kinkajou", "Rainforest mammal with a prehensile tail", 3),
        word("Lorikeet", "Colorful parrot with a brush-tipped tongue", 3),
        word("Markhor", "Wild goat with spiral horns", 3),
        word("Numbat", "Australian marsupial that feeds on termites", 3),
        word("Okapi", "Forest relative of the giraffe with striped legs", 3),
        word("Pademelon", "Small marsupial related to wallabies", 3),
        word("Quetzal", "Bird famous for its iridescent green feathers", 3),
        word("Red Panda", "Tree-dwelling mammal with a ringed tail", 2),
        word("Saiga", "Antelope with an unusual inflated nose", 3),
        word("Tamarin", "Small monkey with claw-like nails", 3),
        word("Urial", "Wild sheep from Central and South Asia", 3),
        word("Vicuna", "Andean camelid prized for fine wool", 3),
        word("Whimbrel", "Long-billed migratory shorebird", 3),
        word("Xray Tetra", "Transparent freshwater fish", 3),
        word("Yabby", "Australian freshwater crayfish", 3),
        word("Zebu", "Humped domestic cattle adapted to hot climates", 2),
        word("Agouti", "Rodent known for burying seeds in forests", 3),
        word("Bonobo", "Great ape closely related to chimpanzees", 2),
        word("Capybara", "Large semiaquatic rodent from South America", 2),
        word("Dhole", "Wild dog that hunts in packs", 3),
        word("Emu", "Large flightless bird from Australia", 2),
        word("Fennec", "Small fox with oversized ears", 2),
        word("Genet", "Slender spotted mammal from Africa and Europe", 3),
        word("Hartebeest", "African antelope with an elongated face", 3),
        word("Ibis", "Wading bird with a long curved bill", 2),
        word("Javelina", "Pig-like mammal of the Americas", 3),
        word("Kea", "Highly intelligent alpine parrot", 3),
        word("Leafcutter Ant", "Ant that farms fungus underground", 3),
        word("Marmoset", "Tiny monkey with clawed fingers", 3),
        word("Nightjar", "Nocturnal bird with a wide mouth", 3),
        word("Orca", "Ocean predator also called a killer whale", 2),
        word("Peccary", "Hog-like mammal with scent glands", 3),
        word("Quagga", "Extinct zebra relative with partial striping", 3),
        word("Rorqual", "Large whale with throat pleats", 3),
        word("Shoebill", "Tall African bird with a massive bill", 3),
        word("Tenrec", "Insect-eating mammal from Madagascar", 3),
        word("Uromastyx", "Spiny-tailed lizard from arid regions", 3),
        word("Vervet", "African monkey known for alarm calls", 3),
        word("Weta", "Large flightless insect from New Zealand", 3),
        word("Xeme", "Small gull of Arctic coasts", 3),
        word("Yellowthroat", "Warbler with a black facial mask", 3),
        word("Zokor", "Burrowing rodent from Asia", 3),
        word("Albatross", "Ocean bird with an enormous wingspan", 2),
        word("Babirusa", "Wild pig with upward-curving tusks", 3),
        word("Civet", "Mammal once associated with perfume production", 3),
        word("Dik Dik", "Tiny antelope with a pointed snout", 3),
        word("Eider", "Sea duck valued for soft down feathers", 3),
        word("Fisher", "Forest mustelid related to martens", 3),
        word("Guineafowl", "Speckled ground bird native to Africa", 3),
        word("Honeyguide", "Bird known for leading humans to beehives", 3),
        word("Impala", "Graceful antelope famous for leaping", 2),
        word("Jacana", "Wading bird with extremely long toes", 3),
        word("Kudu", "Antelope with elegant spiral horns", 3),
        word("Lapwing", "Plover with a crest and erratic flight", 3),
        word("Moorhen", "Wetland bird with large feet", 2),
        word("Nighthawk", "Bird active at dusk with acrobatic flight", 2),
        word("Osprey", "Fish-eating raptor with reversible outer toes", 2),
        word("Pika", "Small mountain mammal related to rabbits", 3),
        word("Quahog", "Edible hard-shelled clam", 3),
        word("Rhea", "Large South American flightless bird", 2),
        word("Sifaka", "Lemur that moves with sideways hops", 3),
        word("Tragopan", "Colorful pheasant with inflatable wattles", 3),
        word("Viscacha", "Rodent resembling a rabbit-chinchilla hybrid", 3)
    ]

    private static let geography: [HangmanWord] = [
        word("Archipelago", "Chain or cluster of islands", 2),
        word("Atacama Desert", "Extremely dry desert on South America's Pacific coast", 3),
        word("Baffin Island", "Massive Arctic island in Canada", 3),
        word("Cape Horn", "Windy headland at South America's southern tip", 3),
        word("Danube Delta", "Wetland where a major European river meets the Black Sea", 3),
        word("Ethiopian Highlands", "Mountainous region often called the roof of Africa", 3),
        word("Faroe Islands", "North Atlantic islands between Iceland and Norway", 3),
        word("Gobi Desert", "Cold desert spanning Mongolia and China", 2),
        word("Ha Long Bay", "Vietnamese bay famous for limestone pillars", 3),
        word("Iberian Peninsula", "Peninsula containing Spain and Portugal", 2),
        word("Java Sea", "Sea bordered by Indonesian islands", 3),
        word("Kalahari", "Semi-arid sandy region of southern Africa", 2),
        word("Lake Baikal", "Deep Siberian lake holding vast freshwater reserves", 3),
        word("Mekong Delta", "Fertile delta in southern Vietnam", 3),
        word("Namib Desert", "Coastal desert known for towering dunes", 3),
        word("Ouagadougou", "Capital of Burkina Faso", 3),
        word("Patagonian Steppe", "Dry grassland region in southern Argentina", 3),
        word("Qinghai Lake", "Large salt lake on the Tibetan Plateau", 3),
        word("Rift Valley", "Long trench formed by tectonic plates", 2),
        word("Strait of Malacca", "Busy sea passage between Malaysia and Sumatra", 3),
        word("Tibetan Plateau", "High plateau often called the roof of the world", 3),
        word("Ural Mountains", "Range often considered part of Europe's boundary", 2),
        word("Ulaanbaatar", "Capital of Mongolia", 3),
        word("Weddell Sea", "Antarctic sea known for dense sea ice", 3),
        word("Yangtze River", "Longest river in Asia", 2),
        word("Zagros Mountains", "Mountain chain stretching across Iran", 3),
        word("Aegean Sea", "Body of water between Greece and Turkey", 2),
        word("Balkan Peninsula", "Peninsula in southeastern Europe", 2),
        word("Caspian Sea", "World's largest inland body of water", 2),
        word("Drake Passage", "Rough ocean corridor south of Cape Horn", 3),
        word("Erie Canal", "Historic waterway linking the Hudson River to the Great Lakes", 3),
        word("Fiordland", "Southwestern New Zealand region of dramatic fjords", 3),
        word("Galapagos", "Pacific archipelago linked to evolution studies", 2),
        word("Hindu Kush", "Mountain range extending through Afghanistan and Pakistan", 3),
        word("Naypyidaw", "Capital of Myanmar", 3),
        word("Jutland Peninsula", "Peninsula forming mainland Denmark", 3),
        word("Karakoram", "Asian range containing some of the highest peaks", 3),
        word("Labrador Sea", "North Atlantic sea between Greenland and Canada", 3),
        word("Mariana Trench", "Deep ocean trench in the western Pacific", 3),
        word("Niger Delta", "Oil-rich delta in West Africa", 3),
        word("Okavango Delta", "Inland delta in Botswana", 3),
        word("Pamir Mountains", "High mountain knot in Central Asia", 3),
        word("Queen Charlotte Sound", "New Zealand sound near the Marlborough region", 3),
        word("Rann of Kutch", "Seasonal salt marsh in western India", 3),
        word("Serengeti", "East African plain famous for annual migrations", 2),
        word("Tian Shan", "Mountain system across Central Asia", 3),
        word("Chisinau", "Capital of Moldova", 3),
        word("Vindhya Range", "Central Indian hill system", 3),
        word("Antananarivo", "Capital of Madagascar", 3),
        word("Yucatan Peninsula", "Region separating the Gulf of Mexico and Caribbean", 2),
        word("Zambezi River", "River that flows over Victoria Falls", 2),
        word("Andaman Sea", "Sea east of the Bay of Bengal", 3),
        word("Bering Strait", "Narrow waterway between Alaska and Russia", 2),
        word("Celebes Sea", "Deep sea between the Philippines and Indonesia", 3),
        word("Dardanelles", "Strategic strait in northwestern Turkey", 3),
        word("Euphrates", "Historic river of Mesopotamia", 2),
        word("Flores Island", "Indonesian island east of Sumbawa", 3),
        word("Gulf of Aden", "Waterway connecting the Red Sea and Arabian Sea", 3),
        word("Hudson Bay", "Vast inland sea in northeastern Canada", 2),
        word("Isthmus of Panama", "Narrow land bridge linking North and South America", 2),
        word("Kermadec Islands", "Remote volcanic arc northeast of New Zealand", 3),
        word("Laptev Sea", "Arctic sea north of Siberia", 3),
        word("Massif Central", "Highland region in south-central France", 3),
        word("Nullarbor Plain", "Treeless limestone plain in southern Australia", 3),
        word("Omo Valley", "Region in Ethiopia known for paleoanthropology", 3),
        word("Pyrenees", "Mountain range between Spain and France", 2),
        word("Qattara Depression", "Low-lying desert basin in Egypt", 3),
        word("Red Sea", "Narrow sea between northeast Africa and Arabia", 2),
        word("Svalbard", "Arctic archipelago under Norwegian rule", 3),
        word("Tasman Sea", "Sea between Australia and New Zealand", 2),
        word("Dushanbe", "Capital of Tajikistan", 3),
        word("Bishkek", "Capital of Kyrgyzstan", 3),
        word("Wrangell Mountains", "Volcanic range in Alaska", 3),
        word("Ljubljana", "Capital of Slovenia", 3),
        word("Zanzibar Archipelago", "Island group off the coast of Tanzania", 3),
        word("Aral Sea", "Shrinking lake between Kazakhstan and Uzbekistan", 3),
        word("Bosphorus", "Strait dividing European and Asian Turkey", 3),
        word("Carpathian Mountains", "Arc-shaped range in Central and Eastern Europe", 3),
        word("Dead Sea", "Salt lake bordered by Jordan and Israel", 2),
        word("English Channel", "Waterway separating England and France", 2),
        word("Fertile Crescent", "Historic region linked to early agriculture", 3),
        word("Great Rift Valley", "Long geological trench in East Africa", 3),
        word("Horn of Africa", "Eastern projection of the African continent", 3),
        word("Izu Peninsula", "Peninsula southwest of Tokyo", 3),
        word("Jordan Rift", "Section of the larger Great Rift system", 3),
        word("Kuril Islands", "Volcanic island chain between Japan and Russia", 3),
        word("Loess Plateau", "Chinese plateau known for windblown silt", 3),
        word("Mozambique Channel", "Channel between Madagascar and mainland Africa", 3),
        word("Negev Desert", "Arid region in southern Israel", 3),
        word("Olympic Peninsula", "Peninsula in northwestern Washington State", 2),
        word("Po Valley", "Fertile plain in northern Italy", 2),
        word("Qilian Mountains", "Mountain chain along the edge of the Tibetan Plateau", 3),
        word("Ross Sea", "Antarctic sea near the Ross Ice Shelf", 3),
        word("Sinai Peninsula", "Triangular peninsula connecting Africa and Asia", 2),
        word("Thimphu", "Capital of Bhutan", 3),
        word("Uvs Lake", "Large saline lake in western Mongolia", 3),
        word("Valdai Hills", "Upland area in western Russia", 3),
        word("Wakhan Corridor", "Narrow strip of territory in northeastern Afghanistan", 3),
        word("Yellow Sea", "Sea between China and the Korean Peninsula", 2),
        word("Zanskar Range", "High mountain range in northern India", 3)
    ]

    private static let foods: [HangmanWord] = [
        word("Bouillabaisse", "Provencal seafood stew with aromatic broth", 3),
        word("Carbonnade", "Belgian beef stew simmered with dark beer", 3),
        word("Chilaquiles", "Mexican dish of tortilla chips simmered in salsa", 2),
        word("Tteokbokki", "Korean rice cakes in a spicy sauce", 3),
        word("Escabeche", "Dish preserved or marinated in vinegar", 3),
        word("Feijoada", "Brazilian black bean stew with pork", 2),
        word("Gnocchi", "Italian dumplings often made from potato", 2),
        word("Halloumi", "Brined cheese known for holding its shape on the grill", 2),
        word("Injera", "Fermented flatbread served with Ethiopian dishes", 3),
        word("Jambalaya", "Rice dish with Creole and Cajun roots", 2),
        word("Kedgeree", "Curried rice dish with smoked fish", 3),
        word("Laksa", "Southeast Asian noodle soup with rich broth", 2),
        word("Moussaka", "Layered casserole with eggplant and meat", 2),
        word("Nduja", "Spicy spreadable pork salami from Calabria", 3),
        word("Okonomiyaki", "Japanese savory pancake with mixed toppings", 3),
        word("Panzanella", "Tuscan bread salad with tomatoes", 3),
        word("Quesabirria", "Cheesy tacos served with rich consommé", 3),
        word("Ratatouille", "Stewed vegetable dish from southern France", 2),
        word("Shakshuka", "Eggs poached in spiced tomato sauce", 2),
        word("Tamales", "Corn dough parcels steamed in husks", 2),
        word("Ube Halaya", "Sweet purple yam jam from the Philippines", 3),
        word("Vindaloo", "Spicy curry with Goan-Portuguese roots", 2),
        word("Beef Wellington", "Beef fillet wrapped in pastry", 3),
        word("Xiao Long Bao", "Soup dumplings filled with hot broth", 3),
        word("Yorkshire Pudding", "Baked batter served with roast meals", 2),
        word("Zabaglione", "Italian custard-like dessert whipped with wine", 3),
        word("Arancini", "Fried stuffed rice balls from Sicily", 3),
        word("Bibimbap", "Korean rice bowl topped with mixed ingredients", 2),
        word("Cacciucco", "Tuscan fish stew with tomato broth", 3),
        word("Dolmades", "Stuffed grape leaves common in the eastern Mediterranean", 3),
        word("Enchilada Suiza", "Enchilada topped with a creamy green sauce", 3),
        word("Focaccia", "Italian flat oven-baked bread", 2),
        word("Galantine", "Deboned poultry dish served cold", 3),
        word("Harissa", "North African chili paste", 2),
        word("Idli", "Steamed rice cakes from South India", 3),
        word("Jjajangmyeon", "Korean noodles in black bean sauce", 3),
        word("Katsuobushi", "Dried skipjack tuna flakes used in Japanese cooking", 3),
        word("Lahmacun", "Thin flatbread topped with minced meat", 3),
        word("Menemen", "Turkish scrambled eggs with tomato and peppers", 3),
        word("Nicoise Salad", "Salad associated with Nice and Mediterranean ingredients", 3),
        word("Ossobuco", "Braised veal shank dish from Milan", 3),
        word("Pappardelle", "Wide ribbon pasta", 2),
        word("Qatayef", "Stuffed pancake dessert popular during Ramadan", 3),
        word("Rillettes", "French spread made from slow-cooked meat", 3),
        word("Souvlaki", "Greek skewered meat dish", 2),
        word("Tagliatelle", "Ribbon pasta traditionally served with rich sauces", 2),
        word("Upma", "Savory South Indian semolina breakfast dish", 3),
        word("Vichyssoise", "Chilled leek and potato soup", 3),
        word("Waldorf Salad", "Apple salad with celery and walnuts", 2),
        word("Xacuti", "Goan curry made with toasted spices and coconut", 3),
        word("Yassa", "West African dish marinated with onion and citrus", 3),
        word("Zaru Soba", "Cold buckwheat noodles served with dipping sauce", 3),
        word("Arepas", "Corn cakes common in northern South America", 2),
        word("Biryani", "Layered rice dish scented with spices", 2),
        word("Cevapcici", "Grilled minced meat sausages from the Balkans", 3),
        word("Dashi", "Japanese stock often made with kombu and bonito", 2),
        word("Empanada Gallega", "Large savory pie from Galicia", 3),
        word("Farfalle", "Bow-tie shaped pasta", 2),
        word("Gravlax", "Cured salmon seasoned with dill", 3),
        word("Huevos Rancheros", "Egg dish with tortillas and salsa", 2),
        word("Iskender Kebab", "Turkish kebab served over bread with yogurt", 3),
        word("Jicama Slaw", "Crunchy slaw based on a mild root vegetable", 3),
        word("Kibbeh", "Dish made from bulgur and spiced meat", 3),
        word("Labneh", "Strained yogurt used as a spread or dip", 3),
        word("Muhammara", "Pepper and walnut spread from the Levant", 3),
        word("Nasi Goreng", "Indonesian fried rice with sweet soy notes", 2),
        word("Oyakodon", "Japanese bowl of chicken, egg, and rice", 3),
        word("Pastilla", "Moroccan pie blending savory and sweet flavors", 3),
        word("Quenelle", "Light dumpling traditionally made from fish or meat", 3),
        word("Romesco", "Catalan sauce with peppers and nuts", 3),
        word("Sabich", "Israeli pita sandwich with eggplant and egg", 3),
        word("Tonkotsu", "Pork-bone broth style of ramen", 2),
        word("Uttapam", "South Indian pancake topped with vegetables", 3),
        word("Vermicelli Bowl", "Rice noodle bowl common in Vietnamese cuisine", 3),
        word("Waterzooi", "Belgian stew of chicken or fish in creamy broth", 3),
        word("Xinxim", "Brazilian stew with shrimp, coconut, and palm oil", 3),
        word("Yakitori", "Japanese grilled chicken skewers", 2),
        word("Ziti al Forno", "Oven-baked pasta with sauce and cheese", 3),
        word("Avgolemono", "Greek soup thickened with egg and lemon", 3),
        word("Baklava", "Layered pastry filled with nuts and syrup", 2),
        word("Cassoulet", "Slow-cooked bean casserole from southern France", 3),
        word("Dan Dan Noodles", "Spicy Sichuan noodles with sesame and chili", 3),
        word("Etouffee", "Cajun or Creole smothered shellfish dish", 3),
        word("Frittata", "Italian open-faced egg dish", 2),
        word("Goulash", "Paprika-rich stew from Central Europe", 2),
        word("Hotteok", "Sweet Korean filled pancake", 3),
        word("Ikan Bakar", "Southeast Asian grilled fish dish", 3),
        word("Jollof Rice", "West African tomato-based rice dish", 2),
        word("Knafeh", "Levantine dessert with cheese and crisp pastry", 3),
        word("Loco Moco", "Hawaiian dish with rice, burger patty, and gravy", 3),
        word("Mapo Tofu", "Sichuan tofu dish with numbing chili heat", 3),
        word("Nasi Lemak", "Coconut rice dish considered iconic in Malaysia", 2),
        word("Orecchiette", "Ear-shaped pasta from southern Italy", 3),
        word("Pozole", "Mexican hominy soup often made with pork", 2),
        word("Qorma", "Slow-cooked curry thickened with yogurt or nuts", 3),
        word("Rosti", "Swiss potato pancake with a crisp crust", 3),
        word("Spanakopita", "Greek spinach and feta pastry", 2),
        word("Tabbouleh", "Herb-heavy salad with bulgur and lemon", 2),
        word("Uramaki", "Inside-out style of sushi roll", 3),
        word("Varenyky", "Filled dumplings common in Ukrainian cuisine", 3)
    ]

    private static let objects: [HangmanWord] = [
        word("Astrolabe", "Instrument once used to measure the altitude of stars", 3),
        word("Barometer", "Device that measures atmospheric pressure", 2),
        word("Caliper", "Tool used to measure thickness or diameter", 2),
        word("Decanter", "Vessel used for pouring and aerating liquids", 2),
        word("Eudiometer", "Glass tube used to measure gas volume changes", 3),
        word("Gimlet", "Hand tool for boring small holes", 3),
        word("Halberd", "Pole weapon combining an axe blade and spear point", 3),
        word("Incubator", "Enclosed apparatus for controlled heat and growth", 2),
        word("Kiln", "High-temperature oven for ceramics or bricks", 2),
        word("Micrometer", "Precision tool for measuring very small distances", 3),
        word("Oscilloscope", "Instrument that visualizes electrical signals", 3),
        word("Plumb Bob", "Weighted tool used to establish a vertical line", 3),
        word("Quadrant", "Instrument for measuring angles", 3),
        word("Retort", "Heat-resistant vessel used in chemistry", 3),
        word("Sextant", "Navigation instrument for measuring celestial angles", 3),
        word("Theodolite", "Surveying instrument for horizontal and vertical angles", 3),
        word("Trestle", "Support framework used for tables or structures", 2),
        word("Vernier", "Scale used for fine precision measurements", 3),
        word("Xylophone", "Percussion instrument with tuned wooden bars", 2),
        word("Zither", "String instrument played flat on a surface", 3),
        word("Anemometer", "Tool for measuring wind speed", 3),
        word("Blowtorch", "Tool that produces a hot focused flame", 2),
        word("Candelabrum", "Decorative holder with multiple candle arms", 3),
        word("Drafting Compass", "Tool for drawing circles and arcs", 2),
        word("Embosser", "Device that creates raised marks or lettering", 3),
        word("Flange", "Rim or collar used for strength or attachment", 3),
        word("Galvanometer", "Instrument that detects small electric currents", 3),
        word("Haversack", "Bag traditionally carried over one shoulder", 2),
        word("Ice Auger", "Tool used to drill holes through ice", 3),
        word("Jacquard Loom", "Loom that uses punched patterns to weave designs", 3),
        word("Kaleidoscope", "Tube that creates repeating mirrored patterns", 2),
        word("Lathe", "Machine that rotates material for shaping", 3),
        word("Monocle", "Single corrective lens worn in one eye", 2),
        word("Nozzle", "Attachment that controls the direction of fluid flow", 2),
        word("Odometer", "Device that records traveled distance", 2),
        word("Quern", "Ancient hand mill for grinding grain", 3),
        word("Ratchet", "Mechanism allowing motion in only one direction", 2),
        word("Scabbard", "Protective sheath for a blade", 2),
        word("Thimble", "Protective cap worn while sewing", 2),
        word("Valise", "Travel bag with a rigid shape", 3),
        word("Winch", "Mechanical device for winding cable or rope", 2),
        word("Abacus", "Manual counting frame with sliding beads", 2),
        word("Bellows", "Air-pumping device used to intensify a fire", 3),
        word("Carabiner", "Spring-loaded metal clip used in climbing", 2),
        word("Drawknife", "Blade with handles on both ends for shaping wood", 3),
        word("Easel", "Stand used to support an artist's canvas", 2),
        word("Feeler Gauge", "Thin strip used to measure small gaps", 3),
        word("Gnomon", "Part of a sundial that casts the shadow", 3),
        word("Grommet", "Reinforcing ring inserted into material", 3),
        word("Handplane", "Woodworking tool for smoothing timber", 3),
        word("Insulator", "Object that resists electrical or thermal transfer", 2),
        word("Jigsaw", "Power tool with a reciprocating blade", 2),
        word("Keytar", "Portable keyboard worn with a strap", 2),
        word("Linstock", "Tool once used to ignite cannons", 3),
        word("Mortar and Pestle", "Tool for crushing and grinding ingredients", 2),
        word("Nyckelharpa", "Swedish keyed string instrument", 3),
        word("Oarlock", "Fitting that holds an oar in place", 3),
        word("Pulley", "Wheel mechanism used to lift loads", 2),
        word("Quill Pen", "Writing instrument made from a feather shaft", 2),
        word("Rasp", "Coarse file used for shaping material", 2),
        word("Soldering Iron", "Tool used to melt solder onto joints", 2),
        word("Turntable", "Rotating platform used for records or display", 2),
        word("Upholstery Awl", "Pointed tool used in heavy sewing work", 3),
        word("Vise", "Clamping tool fixed to a bench", 2),
        word("Whetstone", "Stone used to sharpen blades", 2),
        word("Xacto Knife", "Precision cutting knife used for detail work", 2),
        word("Yarn Swift", "Device that holds yarn while it is wound", 3),
        word("Zipline Harness", "Safety gear worn for cable descent", 3),
        word("Aperture", "Adjustable opening that controls light", 3),
        word("Bulkhead", "Partition wall inside a ship or aircraft", 3),
        word("Clamp", "Device that holds items tightly together", 2),
        word("Diapason", "Another term for a tuning fork", 3),
        word("Eyepiece", "Lens assembly viewed through in an instrument", 3),
        word("Flywheel", "Heavy rotating wheel that stores momentum", 3),
        word("Grapnel", "Hooked tool used for grabbing or anchoring", 3),
        word("Hinge", "Jointed hardware allowing a panel to swing", 2),
        word("Inkwell", "Container for storing writing ink", 2),
        word("Javelin", "Spear-like implement used in athletics", 2),
        word("Kerosene Lamp", "Lamp that burns fuel in a wick", 2),
        word("Latch", "Fastener that keeps a door or gate closed", 2),
        word("Mainsail", "Principal sail on a sailing vessel", 3),
        word("Needlepoint Frame", "Frame used to hold fabric taut for stitching", 3),
        word("Orrery", "Mechanical model of the solar system", 3),
        word("Pipette", "Tool for transferring small volumes of liquid", 3),
        word("Quadcopter", "Aircraft lifted by four rotors", 2),
        word("Rivet Gun", "Tool that fastens rivets into place", 3),
        word("Sprocket", "Toothed wheel that engages a chain", 3),
        word("Trivet", "Stand used to protect surfaces from hot cookware", 2),
        word("Utility Knife", "Retractable knife for general cutting tasks", 2),
        word("Voltage Meter", "Instrument that measures electrical potential", 3),
        word("Whisk", "Kitchen tool for blending and aerating", 2),
        word("Xylorimba", "Percussion instrument combining marimba and xylophone ranges", 3),
        word("Yardarm", "Horizontal spar attached to a ship's mast", 3),
        word("Zirconia Blade", "Ceramic blade known for hard sharp edges", 3),
        word("Anchor Windlass", "Mechanism used to raise and lower an anchor", 3),
        word("Breadboard", "Board used for prototyping electronic circuits", 3),
        word("Cantilever", "Projecting support fixed at one end", 3),
        word("Divot Tool", "Small tool used to repair turf on a green", 3),
        word("Endoscope", "Instrument used to view inside the body", 3),
        word("Fresnel Lens", "Stepped lens designed to focus light efficiently", 3)
    ]

    private static func word(_ answer: String, _ hint: String, _ difficulty: Int) -> HangmanWord {
        HangmanWord(answer: answer, hint: hint, difficulty: difficulty)
    }

    private static func leveledWords(from words: [HangmanWord]) -> [GameLevel: [HangmanWord]] {
        let sortedWords = words.sorted { left, right in
            complexityScore(for: left) < complexityScore(for: right)
        }

        let easyCount = max(1, Int(round(Double(sortedWords.count) * 0.34)))
        let mediumCount = max(1, Int(round(Double(sortedWords.count) * 0.33)))
        let hardStart = min(sortedWords.count, easyCount + mediumCount)

        let easyWords = Array(sortedWords.prefix(easyCount)).map { word in
            HangmanWord(answer: word.answer, hint: word.hint, difficulty: 1)
        }
        let mediumWords = Array(sortedWords.dropFirst(easyCount).prefix(mediumCount)).map { word in
            HangmanWord(answer: word.answer, hint: word.hint, difficulty: 2)
        }
        let hardWords = Array(sortedWords.dropFirst(hardStart)).map { word in
            HangmanWord(answer: word.answer, hint: word.hint, difficulty: 3)
        }

        return [
            .easy: easyWords,
            .medium: mediumWords,
            .hard: hardWords
        ]
    }

    private static func complexityScore(for word: HangmanWord) -> Int {
        let trimmedAnswer = word.answer.replacingOccurrences(of: Strings.Game.blankCharacter, with: "")
        let uniqueLetters = Set(trimmedAnswer.uppercased()).count
        let wordCount = word.answer.split(separator: Character(Strings.Game.blankCharacter)).count
        let rareLetterCount = trimmedAnswer.uppercased().filter { "QXZJVKYW".contains($0) }.count

        return (trimmedAnswer.count * 4)
            + (uniqueLetters * 3)
            + (max(wordCount - 1, 0) * 6)
            + (rareLetterCount * 4)
            + (word.difficulty * 7)
    }
}
